#!/usr/bin/env bash
set -e

# -------------------------------------------------
# Create read-only and read-write users for PostgreSQL
# -------------------------------------------------

# Ensure required environment variables are set
: "${POSTGRESQL_DATA_DB:?Need to set POSTGRESQL_DATA_DB}"
: "${POSTGRESQL_AUTH_DB:?Need to set POSTGRESQL_AUTH_DB}"
: "${POSTGRESQL_SUPERUSER_USER:?Need to set POSTGRESQL_SUPERUSER_USER}"
: "${POSTGRESQL_SUPERUSER_PASSWORD:?Need to set POSTGRESQL_SUPERUSER_PASSWORD}"
: "${POSTGRESQL_RO_USER:?Need to set POSTGRESQL_RO_USER}"
: "${POSTGRESQL_RO_PASSWORD:?Need to set POSTGRESQL_RO_PASSWORD}"
: "${POSTGRESQL_RW_USER:?Need to set POSTGRESQL_RW_USER}"
: "${POSTGRESQL_RW_PASSWORD:?Need to set POSTGRESQL_RW_PASSWORD}"
: "${POSTGRESQL_AUTH_USER:?Need to set POSTGRESQL_AUTH_USER}"
: "${POSTGRESQL_AUTH_PASSWORD:?Need to set POSTGRESQL_AUTH_PASSWORD}"

export PGPASSWORD="$POSTGRESQL_SUPERUSER_PASSWORD"

echo ">>> Creating authorization database: $POSTGRESQL_AUTH_DB..."
psql -v ON_ERROR_STOP=1 -U "$POSTGRESQL_SUPERUSER_USER" -d postgres <<-EOSQL
CREATE DATABASE $POSTGRESQL_AUTH_DB;
EOSQL

echo ">>> Creating authorization user: $POSTGRESQL_AUTH_USER..."
psql -v ON_ERROR_STOP=1 -U "$POSTGRESQL_SUPERUSER_USER" -d "$POSTGRESQL_AUTH_DB" <<-EOSQL
CREATE USER $POSTGRESQL_AUTH_USER WITH PASSWORD '$POSTGRESQL_AUTH_PASSWORD';

GRANT ALL PRIVILEGES ON DATABASE $POSTGRESQL_AUTH_DB TO $POSTGRESQL_AUTH_USER;
GRANT ALL PRIVILEGES ON SCHEMA public TO $POSTGRESQL_AUTH_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRESQL_AUTH_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $POSTGRESQL_AUTH_USER;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $POSTGRESQL_AUTH_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO $POSTGRESQL_AUTH_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO $POSTGRESQL_AUTH_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON FUNCTIONS TO $POSTGRESQL_AUTH_USER;
EOSQL

echo ">>> Creating read-only user: $POSTGRESQL_RO_USER..."
psql -v ON_ERROR_STOP=1 -U "$POSTGRESQL_SUPERUSER_USER" -d "$POSTGRESQL_DATA_DB" <<-EOSQL
CREATE USER $POSTGRESQL_RO_USER WITH PASSWORD '$POSTGRESQL_RO_PASSWORD';

GRANT CONNECT ON DATABASE $POSTGRESQL_DATA_DB TO $POSTGRESQL_RO_USER;
GRANT USAGE ON SCHEMA public TO $POSTGRESQL_RO_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $POSTGRESQL_RO_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO $POSTGRESQL_RO_USER;
EOSQL

echo ">>> Creating read-write user: $POSTGRESQL_RW_USER..."
psql -v ON_ERROR_STOP=1 -U "$POSTGRESQL_SUPERUSER_USER" -d "$POSTGRESQL_DATA_DB" <<-EOSQL
CREATE USER $POSTGRESQL_RW_USER WITH PASSWORD '$POSTGRESQL_RW_PASSWORD';

GRANT CONNECT ON DATABASE $POSTGRESQL_DATA_DB TO $POSTGRESQL_RW_USER;
GRANT USAGE ON SCHEMA public TO $POSTGRESQL_RW_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $POSTGRESQL_RW_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $POSTGRESQL_RW_USER;
EOSQL

echo ">>> Initialization completed successfully!"
