#!/usr/bin/env bash
set -e

# -------------------------------------------------
# Create read-only and read-write users for PostgreSQL
# -------------------------------------------------

# Ensure required environment variables are set
: "${POSTGRESQL_DB:?Need to set POSTGRESQL_DB}"
: "${POSTGRESQL_SUPERUSER_USER:?Need to set POSTGRESQL_SUPERUSER_USER}"
: "${POSTGRESQL_SUPERUSER_PASSWORD:?Need to set POSTGRESQL_SUPERUSER_PASSWORD}"
: "${POSTGRESQL_RO_USER:?Need to set POSTGRESQL_RO_USER}"
: "${POSTGRESQL_RO_PASSWORD:?Need to set POSTGRESQL_RO_PASSWORD}"
: "${POSTGRESQL_RW_USER:?Need to set POSTGRESQL_RW_USER}"
: "${POSTGRESQL_RW_PASSWORD:?Need to set POSTGRESQL_RW_PASSWORD}"

export PGPASSWORD="$POSTGRESQL_SUPERUSER_PASSWORD"

echo ">>> Creating read-only user: $POSTGRESQL_RO_USER..."
psql -v ON_ERROR_STOP=1 -U "$POSTGRESQL_SUPERUSER_USER" -d "$POSTGRESQL_DB" <<-EOSQL
CREATE USER $POSTGRESQL_RO_USER WITH PASSWORD '$POSTGRESQL_RO_PASSWORD';

GRANT CONNECT ON DATABASE $POSTGRESQL_DB TO $POSTGRESQL_RO_USER;
GRANT USAGE ON SCHEMA public TO $POSTGRESQL_RO_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $POSTGRESQL_RO_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO $POSTGRESQL_RO_USER;
EOSQL

echo ">>> Creating read-write user: $POSTGRESQL_RW_USER..."
psql -v ON_ERROR_STOP=1 -U "$POSTGRESQL_SUPERUSER_USER" -d "$POSTGRESQL_DB" <<-EOSQL
CREATE USER $POSTGRESQL_RW_USER WITH PASSWORD '$POSTGRESQL_RW_PASSWORD';

GRANT CONNECT ON DATABASE $POSTGRESQL_DB TO $POSTGRESQL_RW_USER;
GRANT USAGE ON SCHEMA public TO $POSTGRESQL_RW_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $POSTGRESQL_RW_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $POSTGRESQL_RW_USER;
EOSQL

echo ">>> User creation completed successfully!"
