#!/usr/bin/env bash
set -e

# -------------------------------------------------
# Create read-only and read-write users for PostgreSQL
# -------------------------------------------------

# Ensure required environment variables are set
: "${POSTGRESQL_SUPERUSER_USER:?Need to set POSTGRESQL_SUPERUSER_USER}"
: "${POSTGRESQL_SUPERUSER_PASSWORD:?Need to set POSTGRESQL_SUPERUSER_PASSWORD}"

: "${POSTGRESQL_DATA_DB:?Need to set POSTGRESQL_DATA_DB}"
: "${POSTGRESQL_DATA_RO_USER:?Need to set POSTGRESQL_DATA_RO_USER}"
: "${POSTGRESQL_DATA_RO_PASSWORD:?Need to set POSTGRESQL_DATA_RO_PASSWORD}"
: "${POSTGRESQL_DATA_RW_USER:?Need to set POSTGRESQL_DATA_RW_USER}"
: "${POSTGRESQL_DATA_RW_PASSWORD:?Need to set POSTGRESQL_DATA_RW_PASSWORD}"

: "${POSTGRESQL_CONFIG_DB:?Need to set POSTGRESQL_CONFIG_DB}"
: "${POSTGRESQL_CONFIG_USER:?Need to set POSTGRESQL_CONFIG_USER}"
: "${POSTGRESQL_CONFIG_PASSWORD:?Need to set POSTGRESQL_CONFIG_PASSWORD}"

export PGPASSWORD="$POSTGRESQL_SUPERUSER_PASSWORD"

echo ">>> Creating configuration database: $POSTGRESQL_CONFIG_DB..."
psql -v ON_ERROR_STOP=1 -U "$POSTGRESQL_SUPERUSER_USER" -d postgres <<-EOSQL
CREATE DATABASE $POSTGRESQL_CONFIG_DB;
EOSQL

echo ">>> Creating configuration user: $POSTGRESQL_CONFIG_USER..."
psql -v ON_ERROR_STOP=1 -U "$POSTGRESQL_SUPERUSER_USER" -d "$POSTGRESQL_CONFIG_DB" <<-EOSQL
CREATE USER $POSTGRESQL_CONFIG_USER WITH PASSWORD '$POSTGRESQL_CONFIG_PASSWORD';

GRANT ALL PRIVILEGES ON DATABASE $POSTGRESQL_CONFIG_DB TO $POSTGRESQL_CONFIG_USER;
GRANT ALL PRIVILEGES ON SCHEMA public TO $POSTGRESQL_CONFIG_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRESQL_CONFIG_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $POSTGRESQL_CONFIG_USER;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $POSTGRESQL_CONFIG_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO $POSTGRESQL_CONFIG_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO $POSTGRESQL_CONFIG_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON FUNCTIONS TO $POSTGRESQL_CONFIG_USER;
EOSQL


echo ">>> Enabling extensions on $POSTGRESQL_DATA_DB..."
psql -v ON_ERROR_STOP=1 -U "$POSTGRESQL_SUPERUSER_USER" -d "$POSTGRESQL_DATA_DB" <<-EOSQL
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS hstore;
EOSQL

echo ">>> Creating read-only user $POSTGRESQL_DATA_RO_USER for $POSTGRESQL_DATA_DB..."
psql -v ON_ERROR_STOP=1 -U "$POSTGRESQL_SUPERUSER_USER" -d "$POSTGRESQL_DATA_DB" <<-EOSQL
CREATE USER $POSTGRESQL_DATA_RO_USER WITH PASSWORD '$POSTGRESQL_DATA_RO_PASSWORD';

GRANT CONNECT ON DATABASE $POSTGRESQL_DATA_DB TO $POSTGRESQL_DATA_RO_USER;
GRANT USAGE ON SCHEMA public TO $POSTGRESQL_DATA_RO_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $POSTGRESQL_DATA_RO_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO $POSTGRESQL_DATA_RO_USER;
EOSQL

echo ">>> Creating read-write user $POSTGRESQL_DATA_RO_USER for $POSTGRESQL_DATA_DB..."
psql -v ON_ERROR_STOP=1 -U "$POSTGRESQL_SUPERUSER_USER" -d "$POSTGRESQL_DATA_DB" <<-EOSQL
CREATE USER $POSTGRESQL_DATA_RW_USER WITH PASSWORD '$POSTGRESQL_DATA_RW_PASSWORD';

GRANT CONNECT ON DATABASE $POSTGRESQL_DATA_DB TO $POSTGRESQL_DATA_RW_USER;
GRANT USAGE ON SCHEMA public TO $POSTGRESQL_DATA_RW_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $POSTGRESQL_DATA_RW_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $POSTGRESQL_DATA_RW_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO $POSTGRESQL_DATA_RW_USER;

EOSQL

echo ">>> Initialization completed successfully!"
